-- 배포 QA·시연용 데이터. 배포 최소 시드(V900) 뒤에 한 번 적용된다.
-- 시간은 적용 시점 기준으로 13~25시간 뒤에 마감되도록 넣는다. 사진은 위키미디어 커먼즈 공개 이미지(앱 이미지 로더가 식별 UA 를 보낸다).
-- 계정 비밀번호는 모두 Test1234! (bcrypt). 같은 파일을 두 번 돌려도 이메일·제목 기준으로 중복을 넣지 않는다.

-- 1. QA 회원 (판매자 3 · 구매자 3)
INSERT INTO member (email, password, nickname, name, gender, birth_date, phone_number, status, role)
SELECT 'qa.seller1@dib.test', '$2b$10$fCVEIqRzgkoCbtvrpgQLKe37rYCuvGsCv8rnX5QNpX9BVZz4cLURC', '동네전자상가', '김민수', 'MALE', '1992-03-14', '010-7000-0001', 'ACTIVE', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM member WHERE email = 'qa.seller1@dib.test' OR phone_number = '010-7000-0001' OR nickname = '동네전자상가');
INSERT INTO member (email, password, nickname, name, gender, birth_date, phone_number, status, role)
SELECT 'qa.seller2@dib.test', '$2b$10$fCVEIqRzgkoCbtvrpgQLKe37rYCuvGsCv8rnX5QNpX9BVZz4cLURC', '빈티지살롱', '박지현', 'FEMALE', '1996-07-22', '010-7000-0002', 'ACTIVE', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM member WHERE email = 'qa.seller2@dib.test' OR phone_number = '010-7000-0002' OR nickname = '빈티지살롱');
INSERT INTO member (email, password, nickname, name, gender, birth_date, phone_number, status, role)
SELECT 'qa.seller3@dib.test', '$2b$10$fCVEIqRzgkoCbtvrpgQLKe37rYCuvGsCv8rnX5QNpX9BVZz4cLURC', '캠핑장비처분중', '이도윤', 'MALE', '1989-11-02', '010-7000-0003', 'ACTIVE', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM member WHERE email = 'qa.seller3@dib.test' OR phone_number = '010-7000-0003' OR nickname = '캠핑장비처분중');
INSERT INTO member (email, password, nickname, name, gender, birth_date, phone_number, status, role)
SELECT 'qa.buyer1@dib.test', '$2b$10$fCVEIqRzgkoCbtvrpgQLKe37rYCuvGsCv8rnX5QNpX9BVZz4cLURC', '새벽입찰러', '최서연', 'FEMALE', '1998-01-30', '010-7000-0004', 'ACTIVE', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM member WHERE email = 'qa.buyer1@dib.test' OR phone_number = '010-7000-0004' OR nickname = '새벽입찰러');
INSERT INTO member (email, password, nickname, name, gender, birth_date, phone_number, status, role)
SELECT 'qa.buyer2@dib.test', '$2b$10$fCVEIqRzgkoCbtvrpgQLKe37rYCuvGsCv8rnX5QNpX9BVZz4cLURC', '득템장인우진', '정우진', 'MALE', '1994-09-09', '010-7000-0005', 'ACTIVE', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM member WHERE email = 'qa.buyer2@dib.test' OR phone_number = '010-7000-0005' OR nickname = '득템장인우진');
INSERT INTO member (email, password, nickname, name, gender, birth_date, phone_number, status, role)
SELECT 'qa.buyer3@dib.test', '$2b$10$fCVEIqRzgkoCbtvrpgQLKe37rYCuvGsCv8rnX5QNpX9BVZz4cLURC', '미니멀리스트예린', '한예린', 'FEMALE', '2000-05-17', '010-7000-0006', 'ACTIVE', 'USER'
WHERE NOT EXISTS (SELECT 1 FROM member WHERE email = 'qa.buyer3@dib.test' OR phone_number = '010-7000-0006' OR nickname = '미니멀리스트예린');

-- 2. 상품 + 대표 사진
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), (SELECT category_id FROM category WHERE name = '디지털' ORDER BY category_id LIMIT 1), '맥북 에어 M1 2020 13인치 골드 256GB', '재택근무용으로 2년 정도 사용했어요. 배터리 사이클 180회, 외관 잔기스 거의 없고 키보드 멀쩡합니다. 충전기(30W) 포함이고 박스는 없어요. 초기화해서 보내드려요.', 'GOOD', 'MacBook Air M1 (A2337)', 2020, 1390000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Macbook_Air.jpeg/960px-Macbook_Air.jpeg', 'REGISTERED', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '7 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '맥북 에어 M1 2020 13인치 골드 256GB');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '맥북 에어 M1 2020 13인치 골드 256GB' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Macbook_Air.jpeg/960px-Macbook_Air.jpeg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '맥북 에어 M1 2020 13인치 골드 256GB' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), (SELECT category_id FROM category WHERE name = '디지털' ORDER BY category_id LIMIT 1), '아이패드 에어 5세대 64GB 와이파이 + 매직키보드', '학교 과제용으로 쓰다가 노트북으로 바꿔서 정리합니다. 화면 필름 붙여서 썼고 흠집 없어요. 매직 키보드 함께 드립니다(키보드만 새 제품가 40만원대).', 'GOOD', 'iPad Air 5 (M1)', 2022, 929000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/IPad_Air_5th_Generation_2024.jpg/960px-IPad_Air_5th_Generation_2024.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '6 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '7 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/IPad_Air_5th_Generation_2024.jpg/960px-IPad_Air_5th_Generation_2024.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '디지털' ORDER BY category_id LIMIT 1), '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)', '한 달 사용했는데 저랑 귀 모양이 안 맞아서 팝니다. 소독했고 이어팁 S/L 새것 그대로 있어요. 케이스 충전 정상.', 'GOOD', 'SM-R510', 2022, 279000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Samsung_Galaxy_Buds2_Pro_%28Graphite%29.jpg/960px-Samsung_Galaxy_Buds2_Pro_%28Graphite%29.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '8 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Samsung_Galaxy_Buds2_Pro_%28Graphite%29.jpg/960px-Samsung_Galaxy_Buds2_Pro_%28Graphite%29.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '취미/게임/음반' ORDER BY category_id LIMIT 1), '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩', '젤다 엔딩 보고 내놓습니다. 본체 필름 부착, 독·조이콘 정상. 젤다 왕국의 눈물 칩 같이 드려요. 직거래 대전 유성구 가능.', 'GOOD', 'HEG-001', 2021, 415000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Nintendo-Switch-Console-Docked-wJoyConRB.jpg/960px-Nintendo-Switch-Console-Docked-wJoyConRB.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '9 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Nintendo-Switch-Console-Docked-wJoyConRB.jpg/960px-Nintendo-Switch-Console-Docked-wJoyConRB.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), (SELECT category_id FROM category WHERE name = '취미/게임/음반' ORDER BY category_id LIMIT 1), '플레이스테이션5 디스크 에디션 + 듀얼센스 2개', '1년 반 사용. 소음 없고 디스크 정상 인식됩니다. 컨트롤러 하나는 새로 산 화이트예요. 박스·케이블 전부 있습니다.', 'GOOD', 'CFI-1218A', 2023, 688000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/PlayStation_5_and_DualSense.jpg/960px-PlayStation_5_and_DualSense.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '2 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '2 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/PlayStation_5_and_DualSense.jpg/960px-PlayStation_5_and_DualSense.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), (SELECT category_id FROM category WHERE name = '생활가전' ORDER BY category_id LIMIT 1), '다이슨 V11 컴플리트 무선청소기 (헤드 3종)', '이사하면서 건식 로봇청소기로 바꿔 판매합니다. 배터리 40분 정도 갑니다. 헤드 3종, 거치대 포함. 필터는 세척해두었어요.', 'NORMAL', 'Dyson V11 Complete', 2020, 1090000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Dyson_Cordless_Vacuum_%2843141478761%29.jpg/960px-Dyson_Cordless_Vacuum_%2843141478761%29.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '2 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Dyson_Cordless_Vacuum_%2843141478761%29.jpg/960px-Dyson_Cordless_Vacuum_%2843141478761%29.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '생활/주방' ORDER BY category_id LIMIT 1), '발뮤다 더 토스터 K05 블랙', '결혼 선물로 받아 6개월 썼어요. 내부 청소해두었고 물컵 포함. 작동 완벽합니다. 박스 있음.', 'GOOD', 'K05C-BK', 2023, 329000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Balmuda_The_Toaster_%2826332066192%29.jpg/960px-Balmuda_The_Toaster_%2826332066192%29.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '9 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '3 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '발뮤다 더 토스터 K05 블랙');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Balmuda_The_Toaster_%2826332066192%29.jpg/960px-Balmuda_The_Toaster_%2826332066192%29.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), (SELECT category_id FROM category WHERE name = '생활/주방' ORDER BY category_id LIMIT 1), '네스프레소 버츄오 팝 민트 + 캡슐 20개', '카페 자주 가게 돼서 잘 안 쓰네요. 캡슐 20개(멜로지오, 오다시오) 함께 드립니다. 물통 세척 완료.', 'GOOD', 'Vertuo Pop GDV2', 2023, 159000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Nespresso_Vertuo_Pop.jpg/960px-Nespresso_Vertuo_Pop.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '2 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '7 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '네스프레소 버츄오 팝 민트 + 캡슐 20개');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '네스프레소 버츄오 팝 민트 + 캡슐 20개' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Nespresso_Vertuo_Pop.jpg/960px-Nespresso_Vertuo_Pop.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '네스프레소 버츄오 팝 민트 + 캡슐 20개' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '가구/인테리어' ORDER BY category_id LIMIT 1), '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)', '원룸 정리하면서 내놓습니다. 프레임 튼튼하고 쿠션 오염 없어요. 부피가 있어 직거래(대전 서구)나 용달 추천.', 'GOOD', 'POÄNG', 2022, 129000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Po%C3%A4ng_armchairs_at_IKEA_Beijing_Siyuanqiao_Store_%2820210418125708%29.jpg/960px-Po%C3%A4ng_armchairs_at_IKEA_Beijing_Siyuanqiao_Store_%2820210418125708%29.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '2 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Po%C3%A4ng_armchairs_at_IKEA_Beijing_Siyuanqiao_Store_%2820210418125708%29.jpg/960px-Po%C3%A4ng_armchairs_at_IKEA_Beijing_Siyuanqiao_Store_%2820210418125708%29.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), (SELECT category_id FROM category WHERE name = '가구/인테리어' ORDER BY category_id LIMIT 1), '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트', '2년 사용, 사무실 이전으로 판매. 팔걸이·틸트·요추지지 전부 정상. 정품 스티커 있고 기스 거의 없습니다. 서울 강남 직거래.', 'GOOD', 'Aeron Remastered B', 2023, 2190000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Aeron_chair_Brooklyn_Museum.jpg/960px-Aeron_chair_Brooklyn_Museum.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '7 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '7 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Aeron_chair_Brooklyn_Museum.jpg/960px-Aeron_chair_Brooklyn_Museum.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '디지털' ORDER BY category_id LIMIT 1), '캐논 EOS M50 Mark II 화이트 + 15-45mm 번들렌즈', '브이로그용으로 샀다가 폰으로만 찍게 돼서 판매합니다. 셔터 카운트 3천 미만, 렌즈 먼지·곰팡이 없음. 배터리 2개, 64GB SD카드 포함.', 'GOOD', 'EOS M50 Mark II', 2021, 799000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Canon_EOS_M50_Mark_II.jpg/960px-Canon_EOS_M50_Mark_II.jpg', 'REGISTERED', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '2 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '캐논 EOS M50 Mark II 화이트 + 15-45mm 번들렌즈');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '캐논 EOS M50 Mark II 화이트 + 15-45mm 번들렌즈' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Canon_EOS_M50_Mark_II.jpg/960px-Canon_EOS_M50_Mark_II.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '캐논 EOS M50 Mark II 화이트 + 15-45mm 번들렌즈' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), (SELECT category_id FROM category WHERE name = '디지털' ORDER BY category_id LIMIT 1), '후지필름 X100V 실버 (박스·필터·후드 풀셋)', '여행용으로 아껴 쓴 물건입니다. 셔터 8천 컷, 스크래치 없이 깨끗해요. UV필터·후드·추가 배터리까지 다 드립니다. 요즘 구하기 힘든 모델이에요.', 'GOOD', 'X100V', 2020, 1890000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Fujifilm_X100V_9_feb_2020b.jpg/960px-Fujifilm_X100V_9_feb_2020b.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '8 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '7 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Fujifilm_X100V_9_feb_2020b.jpg/960px-Fujifilm_X100V_9_feb_2020b.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), (SELECT category_id FROM category WHERE name = '디지털' ORDER BY category_id LIMIT 1), '소니 WH-1000XM4 블랙 노이즈캔슬링 헤드폰', '출퇴근용 1년 사용. 이어패드 살짝 눌림 있지만 찢어진 곳 없어요. 케이스·케이블·항공어댑터 포함. 배터리 하루 넉넉합니다.', 'NORMAL', 'WH-1000XM4', 2021, 449000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Sony-WH-1000XM3-kabellose-Bluetooth-Noise-Cancelling-Kopfhoerer.jpg/960px-Sony-WH-1000XM3-kabellose-Bluetooth-Noise-Cancelling-Kopfhoerer.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '8 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '4 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '소니 WH-1000XM4 블랙 노이즈캔슬링 헤드폰');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '소니 WH-1000XM4 블랙 노이즈캔슬링 헤드폰' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Sony-WH-1000XM3-kabellose-Bluetooth-Noise-Cancelling-Kopfhoerer.jpg/960px-Sony-WH-1000XM3-kabellose-Bluetooth-Noise-Cancelling-Kopfhoerer.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '소니 WH-1000XM4 블랙 노이즈캔슬링 헤드폰' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), (SELECT category_id FROM category WHERE name = '생활/주방' ORDER BY category_id LIMIT 1), '스탠리 퀜처 H2.0 텀블러 40oz 크림', '선물 받았는데 같은 게 두 개라 한 개 팝니다. 미개봉 새 제품, 택 그대로 있어요.', 'GOOD', 'Quencher H2.0 FlowState 40oz', 2024, 62000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Stanley_Quencher_H2.0_Tumbler_%E2%80%94Limit_2_per_customer.png/960px-Stanley_Quencher_H2.0_Tumbler_%E2%80%94Limit_2_per_customer.png', 'REGISTERED', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '6 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '3 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '스탠리 퀜처 H2.0 텀블러 40oz 크림');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '스탠리 퀜처 H2.0 텀블러 40oz 크림' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Stanley_Quencher_H2.0_Tumbler_%E2%80%94Limit_2_per_customer.png/960px-Stanley_Quencher_H2.0_Tumbler_%E2%80%94Limit_2_per_customer.png', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '스탠리 퀜처 H2.0 텀블러 40oz 크림' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '남성패션' ORDER BY category_id LIMIT 1), '나이키 에어포스1 로우 화이트 270mm (커스텀 스우시)', '두 번 신었어요. 스우시 부분 커스텀 페인팅한 제품이라 유니크합니다. 밑창 거의 새것. 박스 포함.', 'GOOD', 'CW2288-111', 2023, 139000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Customize_White_Nike_Air_Force_One.jpg/960px-Customize_White_Nike_Air_Force_One.jpg', 'REGISTERED', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '6 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '7 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '나이키 에어포스1 로우 화이트 270mm (커스텀 스우시)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '나이키 에어포스1 로우 화이트 270mm (커스텀 스우시)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Customize_White_Nike_Air_Force_One.jpg/960px-Customize_White_Nike_Air_Force_One.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '나이키 에어포스1 로우 화이트 270mm (커스텀 스우시)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), (SELECT category_id FROM category WHERE name = '남성패션' ORDER BY category_id LIMIT 1), '노스페이스 눕시 1996 패딩 블랙 L (95~100)', '작년 겨울 한 시즌 입었습니다. 오염·찢김 없고 드라이클리닝 완료. 봄이라 정리해요. 정품 택 사진 확인 가능.', 'GOOD', '1996 Retro Nuptse', 2023, 379000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/The_North_Face_Mountain_Light_Triclimate_Down_Jacket.jpg/960px-The_North_Face_Mountain_Light_Triclimate_Down_Jacket.jpg', 'REGISTERED', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '2 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '6 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '노스페이스 눕시 1996 패딩 블랙 L (95~100)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '노스페이스 눕시 1996 패딩 블랙 L (95~100)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/The_North_Face_Mountain_Light_Triclimate_Down_Jacket.jpg/960px-The_North_Face_Mountain_Light_Triclimate_Down_Jacket.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '노스페이스 눕시 1996 패딩 블랙 L (95~100)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), (SELECT category_id FROM category WHERE name = '디지털' ORDER BY category_id LIMIT 1), '킨들 페이퍼화이트 11세대 16GB 블랙 + 케이스', '영어 원서 읽으려고 샀는데 결국 종이책으로… 잠금 해제된 상태로 초기화해 드립니다. 자석 케이스 포함, 화면 잔상 없음.', 'GOOD', 'Kindle Paperwhite 11th', 2023, 219000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/2023_Amazon_Kindle_Paperwhite_%282%29.jpg/960px-2023_Amazon_Kindle_Paperwhite_%282%29.jpg', 'REGISTERED', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '4 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '4 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '킨들 페이퍼화이트 11세대 16GB 블랙 + 케이스');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '킨들 페이퍼화이트 11세대 16GB 블랙 + 케이스' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/2023_Amazon_Kindle_Paperwhite_%282%29.jpg/960px-2023_Amazon_Kindle_Paperwhite_%282%29.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '킨들 페이퍼화이트 11세대 16GB 블랙 + 케이스' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '취미/게임/음반' ORDER BY category_id LIMIT 1), '레고 스타워즈 75257 밀레니엄 팔콘 (조립 완성품)', '완성해서 장식장에 두었던 거예요. 부품 누락 없고 미니피그 7개 전부 있습니다. 설명서·박스 있음. 택배 시 분해해서 보내드릴 수 있어요.', 'GOOD', '75257', 2019, 229900, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Millennium_falcon_lego.jpg/960px-Millennium_falcon_lego.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '9 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '9 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '레고 스타워즈 75257 밀레니엄 팔콘 (조립 완성품)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '레고 스타워즈 75257 밀레니엄 팔콘 (조립 완성품)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Millennium_falcon_lego.jpg/960px-Millennium_falcon_lego.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '레고 스타워즈 75257 밀레니엄 팔콘 (조립 완성품)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), (SELECT category_id FROM category WHERE name = '스포츠/레저' ORDER BY category_id LIMIT 1), '헬리녹스 그라운드 체어 블랙', '캠핑 5회 정도 사용. 프레임 정상, 시트 오염 없어요. 수납 파우치 포함. 가볍고 낮은 체어 찾는 분께 추천.', 'GOOD', 'Ground Chair', 2022, 179000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Helinox_Ground_Chair_1.jpg/960px-Helinox_Ground_Chair_1.jpg', 'REGISTERED', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '3 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '8 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '헬리녹스 그라운드 체어 블랙');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '헬리녹스 그라운드 체어 블랙' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Helinox_Ground_Chair_1.jpg/960px-Helinox_Ground_Chair_1.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '헬리녹스 그라운드 체어 블랙' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), (SELECT category_id FROM category WHERE name = '스포츠/레저' ORDER BY category_id LIMIT 1), '브롬톤 M6L 블랙 라커 2021 (가방·펌프 포함)', '출근용으로 2년 탔습니다. 체인·스프라켓 교체 6개월, 브레이크 패드 새것. 프론트 캐리어 블록과 T백, 펌프 같이 드려요. 시운전 환영(대전 둔산).', 'NORMAL', 'M6L', 2021, 2450000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Brompton%2C_Velo_24%2C_Berlin_%28VB243556%29.jpg/960px-Brompton%2C_Velo_24%2C_Berlin_%28VB243556%29.jpg', 'REGISTERED', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '브롬톤 M6L 블랙 라커 2021 (가방·펌프 포함)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '브롬톤 M6L 블랙 라커 2021 (가방·펌프 포함)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Brompton%2C_Velo_24%2C_Berlin_%28VB243556%29.jpg/960px-Brompton%2C_Velo_24%2C_Berlin_%28VB243556%29.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '브롬톤 M6L 블랙 라커 2021 (가방·펌프 포함)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), (SELECT category_id FROM category WHERE name = '디지털' ORDER BY category_id LIMIT 1), '키크론 K4 V2 무선 기계식 키보드 (갈축, RGB)', '적축으로 바꿔서 판매. 키캡 마모 거의 없고 스위치 전부 정상. 알루미늄 프레임, 케이블 포함.', 'GOOD', 'K4 V2 Brown', 2022, 129000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Keychron_K4_mechanical_keyboard.jpg/960px-Keychron_K4_mechanical_keyboard.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '6 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '키크론 K4 V2 무선 기계식 키보드 (갈축, RGB)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '키크론 K4 V2 무선 기계식 키보드 (갈축, RGB)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Keychron_K4_mechanical_keyboard.jpg/960px-Keychron_K4_mechanical_keyboard.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '키크론 K4 V2 무선 기계식 키보드 (갈축, RGB)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '디지털' ORDER BY category_id LIMIT 1), '로지텍 MX Master 3S 그라파이트', '재택 끝나서 정리합니다. 스크롤·클릭 정상, 배터리 한 달 이상 감. USB-C 케이블 포함, 리시버는 로지볼트.', 'GOOD', 'MX Master 3S', 2023, 139000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/2017_Mysz_komputerowa_Logitech_MX_Master.jpg/960px-2017_Mysz_komputerowa_Logitech_MX_Master.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '8 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '4 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '로지텍 MX Master 3S 그라파이트');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '로지텍 MX Master 3S 그라파이트' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/2017_Mysz_komputerowa_Logitech_MX_Master.jpg/960px-2017_Mysz_komputerowa_Logitech_MX_Master.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '로지텍 MX Master 3S 그라파이트' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), (SELECT category_id FROM category WHERE name = '식물' ORDER BY category_id LIMIT 1), '몬스테라 델리시오사 대품 (화분 포함, 높이 약 1m)', '3년 키운 아이인데 이사 가는 집에 자리가 없어요. 새잎 계속 나오고 뿌리 건강합니다. 토분 포함. 직거래만 가능해요(대전 유성).', 'GOOD', NULL, NULL, 90000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Indoor_Monstera_deliciosa.jpg/960px-Indoor_Monstera_deliciosa.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '3 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '몬스테라 델리시오사 대품 (화분 포함, 높이 약 1m)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '몬스테라 델리시오사 대품 (화분 포함, 높이 약 1m)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Indoor_Monstera_deliciosa.jpg/960px-Indoor_Monstera_deliciosa.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '몬스테라 델리시오사 대품 (화분 포함, 높이 약 1m)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '반려동물용품' ORDER BY category_id LIMIT 1), '강아지 이동가방 소형견용 (체크, 5kg 이하)', '말티즈 키울 때 병원 갈 때만 몇 번 썼어요. 세탁 완료, 지퍼·어깨끈 정상. 안에 방석 포함.', 'GOOD', NULL, NULL, 59000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Plaid_Small_Dog_Carrier_Bag_Suspended_by_its_Strap.jpg/960px-Plaid_Small_Dog_Carrier_Bag_Suspended_by_its_Strap.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '3 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '9 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '강아지 이동가방 소형견용 (체크, 5kg 이하)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '강아지 이동가방 소형견용 (체크, 5kg 이하)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Plaid_Small_Dog_Carrier_Bag_Suspended_by_its_Strap.jpg/960px-Plaid_Small_Dog_Carrier_Bag_Suspended_by_its_Strap.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '강아지 이동가방 소형견용 (체크, 5kg 이하)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), (SELECT category_id FROM category WHERE name = '도서' ORDER BY category_id LIMIT 1), '해리포터 시리즈 전권 세트 (문학수첩, 20주년 개정판)', '1권부터 7권까지 전부 있고 한 번 정독했어요. 책등 색 바램 없이 깨끗합니다. 아이 선물로도 좋아요.', 'GOOD', NULL, 2019, 165000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Harry_Potter_books_in_Georgian1768.jpg/960px-Harry_Potter_books_in_Georgian1768.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '6 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '7 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '해리포터 시리즈 전권 세트 (문학수첩, 20주년 개정판)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '해리포터 시리즈 전권 세트 (문학수첩, 20주년 개정판)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Harry_Potter_books_in_Georgian1768.jpg/960px-Harry_Potter_books_in_Georgian1768.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '해리포터 시리즈 전권 세트 (문학수첩, 20주년 개정판)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '여성의류' ORDER BY category_id LIMIT 1), '버버리 스타일 싱글 트렌치코트 베이지 (여성 55)', '봄·가을 두 시즌 입었어요. 안감 상태 좋고 벨트 포함. 세탁 후 보관 중. 키 160~165 분께 맞아요.', 'GOOD', NULL, 2022, 189000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Trenchcoat_worn_by_President_Gerald_R._Ford.jpg/960px-Trenchcoat_worn_by_President_Gerald_R._Ford.jpg', 'REGISTERED', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '2 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '6 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '버버리 스타일 싱글 트렌치코트 베이지 (여성 55)');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '버버리 스타일 싱글 트렌치코트 베이지 (여성 55)' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Trenchcoat_worn_by_President_Gerald_R._Ford.jpg/960px-Trenchcoat_worn_by_President_Gerald_R._Ford.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '버버리 스타일 싱글 트렌치코트 베이지 (여성 55)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), (SELECT category_id FROM category WHERE name = '여성잡화' ORDER BY category_id LIMIT 1), '피엘라벤 칸켄 클래식 백팩 옥스레드', '학교 다닐 때 1년 사용. 모서리 살짝 닳음 있지만 오염 없어요. 방수 원단 정상.', 'NORMAL', 'Kånken Classic', 2022, 118000, 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Fj%C3%A4llr%C3%A4ven_K%C3%A5nken_backpacks.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '6 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '5 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '피엘라벤 칸켄 클래식 백팩 옥스레드');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '피엘라벤 칸켄 클래식 백팩 옥스레드' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Fj%C3%A4llr%C3%A4ven_K%C3%A5nken_backpacks.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '피엘라벤 칸켄 클래식 백팩 옥스레드' ORDER BY product_id DESC LIMIT 1));
INSERT INTO product (member_id, category_id, title, description, condition, model_name, release_year, market_price, thumbnail_url, status, moderation_stage, moderated_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT category_id FROM category WHERE name = '생활/주방' ORDER BY category_id LIMIT 1), '르크루제 시그니처 무쇠 냄비 22cm 체리레드', '선물 받아 두 번 사용했어요. 내부 코팅 흠집 없고 뚜껑·손잡이 정상. 박스 없이 보내드립니다.', 'GOOD', 'Signature Round 22', 2023, 419000, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Le_Creuset_Enamel_Cast_Iron_Cookware.jpg/960px-Le_Creuset_Enamel_Cast_Iron_Cookware.jpg', 'ON_AUCTION', 'rule', (NOW() AT TIME ZONE 'UTC') - INTERVAL '2 days', (NOW() AT TIME ZONE 'UTC') - INTERVAL '9 days'
WHERE NOT EXISTS (SELECT 1 FROM product WHERE title = '르크루제 시그니처 무쇠 냄비 22cm 체리레드');
INSERT INTO product_image (product_id, image_url, sequence)
SELECT (SELECT product_id FROM product WHERE title = '르크루제 시그니처 무쇠 냄비 22cm 체리레드' ORDER BY product_id DESC LIMIT 1), 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Le_Creuset_Enamel_Cast_Iron_Cookware.jpg/960px-Le_Creuset_Enamel_Cast_Iron_Cookware.jpg', 1 WHERE NOT EXISTS (SELECT 1 FROM product_image WHERE product_id = (SELECT product_id FROM product WHERE title = '르크루제 시그니처 무쇠 냄비 22cm 체리레드' ORDER BY product_id DESC LIMIT 1));

-- 3. 진행 중 경매 (13~25시간 남음) 와 입찰
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드' ORDER BY product_id DESC LIMIT 1), 450000, 480000, 93540, (NOW() AT TIME ZONE 'UTC') - INTERVAL '90 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1469 minutes', 'ACTIVE', 2, 2, 78, (NOW() AT TIME ZONE 'UTC') - INTERVAL '120 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 460000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '60 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 460000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 480000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '30 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 480000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1), 80000, 85000, 101160, (NOW() AT TIME ZONE 'UTC') - INTERVAL '472 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1214 minutes', 'ACTIVE', 1, 1, 161, (NOW() AT TIME ZONE 'UTC') - INTERVAL '502 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 85000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '236 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 85000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1), 250000, 300000, 69420, (NOW() AT TIME ZONE 'UTC') - INTERVAL '280 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '877 minutes', 'ACTIVE', 4, 3, 155, (NOW() AT TIME ZONE 'UTC') - INTERVAL '310 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 260000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '224 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 260000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 275000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '168 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 275000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 290000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '112 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 290000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 300000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '56 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 300000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1), 400000, 430000, 69660, (NOW() AT TIME ZONE 'UTC') - INTERVAL '339 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '822 minutes', 'ACTIVE', 2, 2, 144, (NOW() AT TIME ZONE 'UTC') - INTERVAL '369 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 410000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '226 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 410000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 430000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '113 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 430000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1), 250000, 300000, 115440, (NOW() AT TIME ZONE 'UTC') - INTERVAL '426 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1498 minutes', 'ACTIVE', 3, 2, 31, (NOW() AT TIME ZONE 'UTC') - INTERVAL '456 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 260000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '320 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 260000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 280000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '213 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 280000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 300000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '107 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 300000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1), 150000, 160000, 67500, (NOW() AT TIME ZONE 'UTC') - INTERVAL '331 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '794 minutes', 'ACTIVE', 1, 1, 42, (NOW() AT TIME ZONE 'UTC') - INTERVAL '361 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 160000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '166 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 160000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '네스프레소 버츄오 팝 민트 + 캡슐 20개' ORDER BY product_id DESC LIMIT 1), 60000, 60000, 76320, (NOW() AT TIME ZONE 'UTC') - INTERVAL '199 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1073 minutes', 'ACTIVE', 0, 0, 21, (NOW() AT TIME ZONE 'UTC') - INTERVAL '229 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '네스프레소 버츄오 팝 민트 + 캡슐 20개' ORDER BY product_id DESC LIMIT 1));
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1), 40000, 50000, 93060, (NOW() AT TIME ZONE 'UTC') - INTERVAL '297 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1254 minutes', 'ACTIVE', 2, 2, 104, (NOW() AT TIME ZONE 'UTC') - INTERVAL '327 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 45000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '198 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 45000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 50000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '99 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 50000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1), 900000, 1000000, 66600, (NOW() AT TIME ZONE 'UTC') - INTERVAL '267 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '843 minutes', 'ACTIVE', 3, 2, 77, (NOW() AT TIME ZONE 'UTC') - INTERVAL '297 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 920000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '201 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 920000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 950000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '134 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 950000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 1000000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '67 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 1000000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1), 1600000, 1850000, 84180, (NOW() AT TIME ZONE 'UTC') - INTERVAL '152 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1251 minutes', 'ACTIVE', 5, 3, 156, (NOW() AT TIME ZONE 'UTC') - INTERVAL '182 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 1650000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '127 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 1650000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 1700000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '102 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 1700000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 1750000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '76 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 1750000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 1800000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '51 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 1800000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 1850000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '26 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 1850000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '소니 WH-1000XM4 블랙 노이즈캔슬링 헤드폰' ORDER BY product_id DESC LIMIT 1), 150000, 175000, 89220, (NOW() AT TIME ZONE 'UTC') - INTERVAL '447 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1040 minutes', 'ACTIVE', 2, 2, 66, (NOW() AT TIME ZONE 'UTC') - INTERVAL '477 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '소니 WH-1000XM4 블랙 노이즈캔슬링 헤드폰' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 160000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '298 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '소니 WH-1000XM4 블랙 노이즈캔슬링 헤드폰' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 160000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 175000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '149 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '소니 WH-1000XM4 블랙 노이즈캔슬링 헤드폰' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 175000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '소니 WH-1000XM4 블랙 노이즈캔슬링 헤드폰' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '레고 스타워즈 75257 밀레니엄 팔콘 (조립 완성품)' ORDER BY product_id DESC LIMIT 1), 100000, 125000, 105120, (NOW() AT TIME ZONE 'UTC') - INTERVAL '302 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1450 minutes', 'ACTIVE', 2, 2, 100, (NOW() AT TIME ZONE 'UTC') - INTERVAL '332 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '레고 스타워즈 75257 밀레니엄 팔콘 (조립 완성품)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 110000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '202 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '레고 스타워즈 75257 밀레니엄 팔콘 (조립 완성품)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 110000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 125000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '101 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '레고 스타워즈 75257 밀레니엄 팔콘 (조립 완성품)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 125000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '레고 스타워즈 75257 밀레니엄 팔콘 (조립 완성품)' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '키크론 K4 V2 무선 기계식 키보드 (갈축, RGB)' ORDER BY product_id DESC LIMIT 1), 50000, 55000, 68280, (NOW() AT TIME ZONE 'UTC') - INTERVAL '316 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '822 minutes', 'ACTIVE', 1, 1, 235, (NOW() AT TIME ZONE 'UTC') - INTERVAL '346 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '키크론 K4 V2 무선 기계식 키보드 (갈축, RGB)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 55000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '158 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '키크론 K4 V2 무선 기계식 키보드 (갈축, RGB)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 55000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '키크론 K4 V2 무선 기계식 키보드 (갈축, RGB)' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '로지텍 MX Master 3S 그라파이트' ORDER BY product_id DESC LIMIT 1), 55000, 65000, 68280, (NOW() AT TIME ZONE 'UTC') - INTERVAL '239 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '899 minutes', 'ACTIVE', 2, 2, 29, (NOW() AT TIME ZONE 'UTC') - INTERVAL '269 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '로지텍 MX Master 3S 그라파이트' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 60000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '160 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '로지텍 MX Master 3S 그라파이트' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 60000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 65000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '80 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '로지텍 MX Master 3S 그라파이트' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 65000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '로지텍 MX Master 3S 그라파이트' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '몬스테라 델리시오사 대품 (화분 포함, 높이 약 1m)' ORDER BY product_id DESC LIMIT 1), 30000, 35000, 113400, (NOW() AT TIME ZONE 'UTC') - INTERVAL '390 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1500 minutes', 'ACTIVE', 2, 2, 188, (NOW() AT TIME ZONE 'UTC') - INTERVAL '420 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '몬스테라 델리시오사 대품 (화분 포함, 높이 약 1m)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 32000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '260 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '몬스테라 델리시오사 대품 (화분 포함, 높이 약 1m)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 32000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 35000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '130 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '몬스테라 델리시오사 대품 (화분 포함, 높이 약 1m)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 35000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '몬스테라 델리시오사 대품 (화분 포함, 높이 약 1m)' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '강아지 이동가방 소형견용 (체크, 5kg 이하)' ORDER BY product_id DESC LIMIT 1), 15000, 15000, 83940, (NOW() AT TIME ZONE 'UTC') - INTERVAL '267 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1132 minutes', 'ACTIVE', 0, 0, 239, (NOW() AT TIME ZONE 'UTC') - INTERVAL '297 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '강아지 이동가방 소형견용 (체크, 5kg 이하)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '해리포터 시리즈 전권 세트 (문학수첩, 20주년 개정판)' ORDER BY product_id DESC LIMIT 1), 45000, 52000, 62880, (NOW() AT TIME ZONE 'UTC') - INTERVAL '112 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '936 minutes', 'ACTIVE', 2, 2, 240, (NOW() AT TIME ZONE 'UTC') - INTERVAL '142 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '해리포터 시리즈 전권 세트 (문학수첩, 20주년 개정판)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 48000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '75 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '해리포터 시리즈 전권 세트 (문학수첩, 20주년 개정판)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 48000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 52000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '38 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '해리포터 시리즈 전권 세트 (문학수첩, 20주년 개정판)' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 52000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '해리포터 시리즈 전권 세트 (문학수첩, 20주년 개정판)' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '피엘라벤 칸켄 클래식 백팩 옥스레드' ORDER BY product_id DESC LIMIT 1), 30000, 33000, 81480, (NOW() AT TIME ZONE 'UTC') - INTERVAL '434 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '924 minutes', 'ACTIVE', 1, 1, 209, (NOW() AT TIME ZONE 'UTC') - INTERVAL '464 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '피엘라벤 칸켄 클래식 백팩 옥스레드' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), 33000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '217 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '피엘라벤 칸켄 클래식 백팩 옥스레드' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 33000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '피엘라벤 칸켄 클래식 백팩 옥스레드' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;
INSERT INTO auction (product_id, start_price, current_price, auction_time, started_at, ended_at, status, bid_count, bidder_count, view_count, created_at)
SELECT (SELECT product_id FROM product WHERE title = '르크루제 시그니처 무쇠 냄비 22cm 체리레드' ORDER BY product_id DESC LIMIT 1), 150000, 175000, 105480, (NOW() AT TIME ZONE 'UTC') - INTERVAL '279 minutes', (NOW() AT TIME ZONE 'UTC') + INTERVAL '1479 minutes', 'ACTIVE', 2, 2, 174, (NOW() AT TIME ZONE 'UTC') - INTERVAL '309 minutes'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '르크루제 시그니처 무쇠 냄비 22cm 체리레드' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), 160000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '186 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '르크루제 시그니처 무쇠 냄비 22cm 체리레드' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 160000);
INSERT INTO bid (auction_id, member_id, amount, created_at)
SELECT a.auction_id, (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), 175000, (NOW() AT TIME ZONE 'UTC') - INTERVAL '93 minutes' FROM auction a WHERE a.product_id = (SELECT product_id FROM product WHERE title = '르크루제 시그니처 무쇠 냄비 22cm 체리레드' ORDER BY product_id DESC LIMIT 1)
AND NOT EXISTS (SELECT 1 FROM bid b WHERE b.auction_id = a.auction_id AND b.amount = 175000);
UPDATE auction a SET top_bid_id = (SELECT b.bid_id FROM bid b WHERE b.auction_id = a.auction_id ORDER BY b.amount DESC LIMIT 1) WHERE a.product_id = (SELECT product_id FROM product WHERE title = '르크루제 시그니처 무쇠 냄비 22cm 체리레드' ORDER BY product_id DESC LIMIT 1) AND a.top_bid_id IS NULL;

-- 4. 예약 라이브와 편성 상품 (짧은 라이브 경매, 방송 시작 때 호스트가 시작)
INSERT INTO live_broadcast (member_id, title, description, status, livekit_room_name, started_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), '동네전자상가 주말 특가 라이브', '맥북·아이패드·카메라 실물 상태 하나하나 보여드려요. 질문은 채팅으로!', 'SCHEDULED', 'qa-live-1', (NOW() AT TIME ZONE 'UTC') + INTERVAL '20 hours', (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM live_broadcast WHERE livekit_room_name = 'qa-live-1');
INSERT INTO auction (product_id, start_price, current_price, auction_time, status, live_broadcast_id, created_at)
SELECT (SELECT product_id FROM product WHERE title = '맥북 에어 M1 2020 13인치 골드 256GB' ORDER BY product_id DESC LIMIT 1), 650000, 650000, 180, 'SCHEDULED', (SELECT live_broadcast_id FROM live_broadcast WHERE livekit_room_name = 'qa-live-1'), (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '맥북 에어 M1 2020 13인치 골드 256GB' ORDER BY product_id DESC LIMIT 1));
INSERT INTO auction (product_id, start_price, current_price, auction_time, status, live_broadcast_id, created_at)
SELECT (SELECT product_id FROM product WHERE title = '캐논 EOS M50 Mark II 화이트 + 15-45mm 번들렌즈' ORDER BY product_id DESC LIMIT 1), 380000, 380000, 180, 'SCHEDULED', (SELECT live_broadcast_id FROM live_broadcast WHERE livekit_room_name = 'qa-live-1'), (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '캐논 EOS M50 Mark II 화이트 + 15-45mm 번들렌즈' ORDER BY product_id DESC LIMIT 1));
INSERT INTO auction (product_id, start_price, current_price, auction_time, status, live_broadcast_id, created_at)
SELECT (SELECT product_id FROM product WHERE title = '킨들 페이퍼화이트 11세대 16GB 블랙 + 케이스' ORDER BY product_id DESC LIMIT 1), 80000, 80000, 180, 'SCHEDULED', (SELECT live_broadcast_id FROM live_broadcast WHERE livekit_room_name = 'qa-live-1'), (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '킨들 페이퍼화이트 11세대 16GB 블랙 + 케이스' ORDER BY product_id DESC LIMIT 1));
INSERT INTO live_broadcast (member_id, title, description, status, livekit_room_name, started_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), '빈티지살롱 옷장 정리 라이브', '한 시즌 입은 아우터와 잡화를 짧은 경매로 빠르게 정리합니다.', 'SCHEDULED', 'qa-live-2', (NOW() AT TIME ZONE 'UTC') + INTERVAL '27 hours', (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM live_broadcast WHERE livekit_room_name = 'qa-live-2');
INSERT INTO auction (product_id, start_price, current_price, auction_time, status, live_broadcast_id, created_at)
SELECT (SELECT product_id FROM product WHERE title = '노스페이스 눕시 1996 패딩 블랙 L (95~100)' ORDER BY product_id DESC LIMIT 1), 170000, 170000, 180, 'SCHEDULED', (SELECT live_broadcast_id FROM live_broadcast WHERE livekit_room_name = 'qa-live-2'), (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '노스페이스 눕시 1996 패딩 블랙 L (95~100)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO auction (product_id, start_price, current_price, auction_time, status, live_broadcast_id, created_at)
SELECT (SELECT product_id FROM product WHERE title = '버버리 스타일 싱글 트렌치코트 베이지 (여성 55)' ORDER BY product_id DESC LIMIT 1), 40000, 40000, 180, 'SCHEDULED', (SELECT live_broadcast_id FROM live_broadcast WHERE livekit_room_name = 'qa-live-2'), (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '버버리 스타일 싱글 트렌치코트 베이지 (여성 55)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO auction (product_id, start_price, current_price, auction_time, status, live_broadcast_id, created_at)
SELECT (SELECT product_id FROM product WHERE title = '나이키 에어포스1 로우 화이트 270mm (커스텀 스우시)' ORDER BY product_id DESC LIMIT 1), 60000, 60000, 180, 'SCHEDULED', (SELECT live_broadcast_id FROM live_broadcast WHERE livekit_room_name = 'qa-live-2'), (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '나이키 에어포스1 로우 화이트 270mm (커스텀 스우시)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO live_broadcast (member_id, title, description, status, livekit_room_name, started_at, created_at)
SELECT (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test'), '캠핑장비 처분 라이브 · 체어부터 자전거까지', '캠핑 은퇴합니다. 체어·텀블러·자전거까지 시운전 영상으로 보여드릴게요.', 'SCHEDULED', 'qa-live-3', (NOW() AT TIME ZONE 'UTC') + INTERVAL '44 hours', (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM live_broadcast WHERE livekit_room_name = 'qa-live-3');
INSERT INTO auction (product_id, start_price, current_price, auction_time, status, live_broadcast_id, created_at)
SELECT (SELECT product_id FROM product WHERE title = '헬리녹스 그라운드 체어 블랙' ORDER BY product_id DESC LIMIT 1), 60000, 60000, 180, 'SCHEDULED', (SELECT live_broadcast_id FROM live_broadcast WHERE livekit_room_name = 'qa-live-3'), (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '헬리녹스 그라운드 체어 블랙' ORDER BY product_id DESC LIMIT 1));
INSERT INTO auction (product_id, start_price, current_price, auction_time, status, live_broadcast_id, created_at)
SELECT (SELECT product_id FROM product WHERE title = '스탠리 퀜처 H2.0 텀블러 40oz 크림' ORDER BY product_id DESC LIMIT 1), 25000, 25000, 180, 'SCHEDULED', (SELECT live_broadcast_id FROM live_broadcast WHERE livekit_room_name = 'qa-live-3'), (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '스탠리 퀜처 H2.0 텀블러 40oz 크림' ORDER BY product_id DESC LIMIT 1));
INSERT INTO auction (product_id, start_price, current_price, auction_time, status, live_broadcast_id, created_at)
SELECT (SELECT product_id FROM product WHERE title = '브롬톤 M6L 블랙 라커 2021 (가방·펌프 포함)' ORDER BY product_id DESC LIMIT 1), 1300000, 1300000, 180, 'SCHEDULED', (SELECT live_broadcast_id FROM live_broadcast WHERE livekit_room_name = 'qa-live-3'), (NOW() AT TIME ZONE 'UTC') - INTERVAL '1 day'
WHERE NOT EXISTS (SELECT 1 FROM auction WHERE product_id = (SELECT product_id FROM product WHERE title = '브롬톤 M6L 블랙 라커 2021 (가방·펌프 포함)' ORDER BY product_id DESC LIMIT 1));

-- 5. 찜 (홈 인기·찜 수 확인용)
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), (SELECT product_id FROM product WHERE title = '맥북 에어 M1 2020 13인치 골드 256GB' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '맥북 에어 M1 2020 13인치 골드 256GB' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), (SELECT product_id FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '아이패드 에어 5세대 64GB 와이파이 + 매직키보드' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '갤럭시 버즈2 프로 그라파이트 (이어팁 새것 포함)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '닌텐도 스위치 OLED 화이트 + 젤다 왕눈 칩' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '플레이스테이션5 디스크 에디션 + 듀얼센스 2개' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '다이슨 V11 컴플리트 무선청소기 (헤드 3종)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '발뮤다 더 토스터 K05 블랙' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), (SELECT product_id FROM product WHERE title = '네스프레소 버츄오 팝 민트 + 캡슐 20개' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '네스프레소 버츄오 팝 민트 + 캡슐 20개' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), (SELECT product_id FROM product WHERE title = '네스프레소 버츄오 팝 민트 + 캡슐 20개' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '네스프레소 버츄오 팝 민트 + 캡슐 20개' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '이케아 포엥 암체어 자작나무 + 쿠션(크니사 다크그레이)' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test'), (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer2@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '허먼밀러 에어론 체어 B사이즈 풀옵션 그라파이트' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test'), (SELECT product_id FROM product WHERE title = '캐논 EOS M50 Mark II 화이트 + 15-45mm 번들렌즈' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer3@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '캐논 EOS M50 Mark II 화이트 + 15-45mm 번들렌즈' ORDER BY product_id DESC LIMIT 1));
INSERT INTO bookmark (member_id, product_id) SELECT (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test'), (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1)
WHERE NOT EXISTS (SELECT 1 FROM bookmark WHERE member_id = (SELECT member_id FROM member WHERE email = 'qa.buyer1@dib.test') AND product_id = (SELECT product_id FROM product WHERE title = '후지필름 X100V 실버 (박스·필터·후드 풀셋)' ORDER BY product_id DESC LIMIT 1));
UPDATE auction a SET bookmark_count = (SELECT COUNT(*) FROM bookmark bm WHERE bm.product_id = a.product_id) WHERE a.product_id IN (SELECT product_id FROM product WHERE member_id IN ((SELECT member_id FROM member WHERE email = 'qa.seller1@dib.test'), (SELECT member_id FROM member WHERE email = 'qa.seller2@dib.test'), (SELECT member_id FROM member WHERE email = 'qa.seller3@dib.test')));
